### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cdc.aggregator.shared-library#22]
**Original report on BitBucket by CESSDA Support Team (GitHub: [cessda](https://github.com/cessda)).**

----------------------------------------

This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

---

### ⚠ Dependency Lookup Warnings ⚠

-   Renovate failed to look up the following dependencies: `kuha_common`.

Files affected: `setup.py`

---

## Open

These updates have all been created already.

 - [#21: Update dependency kuha_common to v2.1.0](../../pull-requests/33)

## Detected dependencies

**pip_requirements**

**requirements.txt**

 - `py12flogging ==0.5.0`
 - `ConfigArgParse ==1.5.3`
 - `tornado ==6.2.0`
 - `kuha_common 2.0.1`

**pip_setup**

**setup.py**

 - `kuha_common >=2.0.1`

**Comment by matthew-morris-cessda** [comment]
Renovate Bot is no longer being used on this repository
